### ISSUE TITLE
Questions about this project

### ISSUE THREAD

**Issue by pidgeon777** [quarkslab/numbat#1]
First of all, congratulations on this project.

I would like to ask if the current Python API implementation covers all of the Sourcetrail DB kind of data/fields, or if some features are still missing.

**Comment by Fenrisfulsur** [comment]
Hello @pidgeon777, 

Thanks for the feedback :)

Yes, this API covers all the basic Sourcetrail data types as you can see [here](https://github.com/quarkslab/numbat/blob/main/src/numbat/types.py). These types directly come from
the original SourceTrail SQLite [tables](https://github.com/CoatiSoftware/Sourcetrail/blob/4b1b0e4fd19c4af235fef12b0564c05348f5f6d3/src/lib/data/storage/sqlite/SqliteIndexStorage.cpp#L1237).

You should be able to manipulate all the types, but some high-level API might be missing. If you have any specific use cases in mind, we could consider adding these functionalities to the existing API.

**Comment by RobinDavid** [comment]
Closing the issue. Please reopen it if a specific feature is missing.
